# Simulated Agent

In [28]:
import numpy as np

In [32]:
class Agent:
    def __init__(self, a0, b0, q):
        self.a0 = a0
        self.b0 = b0
        self.q = q
        self.p = 0.0
        self.pickP()
        self.notPickP()
        
    def pickP(self):#PICK P  FROM BETA DISTRIBUTION
        self.p = np.random.beta(self.a0, self.b0)
    def notPickP(self):
        self.p = 1 - np.random.beta(self.a0, self.b0)
            
    def draw(self):
        if np.random.uniform(0,1) < self.p:
            return True
        else:
            return False
        
    def turn(self):
        if np.random.uniform(0,1) < self.q:
            self.pickP()
        # else:
        #     self.notPickP()
        return self.draw()

In [35]:
ag = Agent(0.1,0.5, 0.1)
n = 8
outcomes = []
prob = []
for i in range(n):
    outcomes.append(ag.turn())


In [36]:
outcomes

[True, True, True, True, False, False, False, False]

In [47]:
n = len(outcomes)
tb = np.zeros((n+1,n+1))
tbl = np.mat((n+1, n+1))
t = []
tb[0,0] = 1
p = 0.0
gm = 0.2
for n in range(tb.shape[0]):
    for m in range(tb.shape[1]):

        def mu(n,m):
            if n==0 and m==0:
                a = 0.1
                b = 0.5
            elif n==0:
                a = 0.1
                b = 0.5 + m
            elif m==0 :
                a = 0.1 + n
                b = 0.5
            else:
                a = 0.1 + n
                b = 0.5 + m
            return a / (a+b)
        # print(n,m)
        # tb[n, m] =  1
        # tb[n, m-1] = 0
        # tbl = tb
        # t.append(tbl)
        for o in outcomes:
            if o :
               tb[n,m] = 1
               tb[n,m] *= (1-gm)
               tb[n-1, m] = 0
               tb[n-1, m] += gm
               u = mu(n-1, m)
               z = tb[n-1,m] + tb[n,m] #gm*tb[n-1,m] + (1-gm)*tb[n,m]
               tb[n,m] = tb[ n-1, m] * u / z
               tb[0, m] = 0
               # print(u, z, tb[n,m])
            else:
                # p = 1 - np.random.beta(0.1 + n, 0.5 + m)
                tb[n,m] = 1
                tb[n,m] *= (1-gm)
                tb[n, m-1] = 0
                tb[n, m-1] += gm
                u = mu(n, m-1)
                z = tb[n ,m-1] + tb[n,m] #gm*tb[n ,m-1] + (1-gm)*tb[n,m]
                tb[n,m] = tb[ n, m-1] * u  / z
                tb[n,0] = 0

        print(o, (n,m), '\n', tb)


False (0, 0) 
 [[0.  0.  0.  0.  0.  0.  0.  0.  0.2]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.2 0.  0.  0.  0.  0.  0.  0.  0. ]]
False (0, 1) 
 [[0.         0.03333333 0.         0.         0.         0.
  0.         0.         0.2       ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.     

In [108]:
class DBMAgent: # n = # of outcomes
    def __init__(self, a0, b0, q, gamma, outcomes):
        self.a0 = a0
        self.b0 = b0
        self.q = q
        self.p = 0.0
        self.outcomes = outcomes
        self.n = len(outcomes)
        self.table = np.zeros((n+1,n+1))
        self.table[0,0] = 1
        self.gamma = gamma
        # self.updateP(outcomes)

    def turn(self):
        for i in range( self.table.shape[0]):
            for j in range(self.table.shape[1]):

                self.table[0,0] = self.gamma
                self.table[i,j] = (1-self.gamma)*self.updateP()
                print(self.p)



        return self.table

In [109]:
agent = DBMAgent(0.1,0.5, 0.1, 0.9, outcomes)

True (0, 0) mu: 0.16666666666666669 z: 0.16666666666666669 p(n,m) 0.0 
 [[0.  0.  0.  0.  0.  0.  0.  0.  0.2]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]]
True (0, 0) mu: 0.16666666666666669 z: 0.16666666666666669 p(n,m) 0.0 
 [[0.  0.  0.  0.  0.  0.  0.  0.  0.2]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]]
True (0, 0) mu: 0.16666666666666669 z: 0.16666666666666669 p(n,m) 0.0 
 [[0.  0.  0.  0.  0.  0.  0.  0.  0.2]
 [0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       ],


In [ ]:
agent.table

In [ ]:
agent.turn()