# Simulated Agent

In [2]:
import numpy as np

In [3]:
class Agent:
    def __init__(self, a0, b0, q):
        self.a0 = a0
        self.b0 = b0
        self.q = q
        self.p = 0.0
        self.pickP()
        self.notPickP()
        
    def pickP(self):#PICK P  FROM BETA DISTRIBUTION
        self.p = np.random.beta(self.a0, self.b0)
    def notPickP(self):
        self.p = 1 - np.random.beta(self.a0, self.b0)
            
    def draw(self):
        if np.random.uniform(0,1) < self.p:
            return True
        else:
            return False
        
    def turn(self):
        if np.random.uniform(0,1) < self.q:
            self.pickP()
        # else:
        #     self.notPickP()
        return self.draw()

In [4]:
ag = Agent(0.1,0.5, 0.1)
n = 8
outcomes = []
prob = []
for i in range(n):
    outcomes.append(ag.turn())


In [5]:
outcomes

[True, True, True, True, True, True, False, False]

In [7]:
class DBMAgent:
    def __init__(self, a0, b0, q, gamma, outcomes):
        self.a0 = a0
        self.b0 = b0
        self.q = q
        self.p = 0.0
        self.outcomes = outcomes
        self.num = len(outcomes)
        self.tb = np.zeros((self.num + 1, self.num + 1))
        self.tb[0, 0] = 1
        self.gamma = gamma

    def likelihood(self):
        pass

    def mu(self, i, j):
        self.a0 = self.a0 + i
        self.b0 = self.b0 + j
        return self.a0 / (self.a0 + self.b0)

    def turn(self):

        for o in self.outcomes:
            tb_new = self.tb.copy()

            for n in range(self.tb.shape[0]):
                for m in range(self.tb.shape[1]):
                    if n == 0 and m == 0:
                        self.tb[n, m] = self.tb[n, m] + self.gamma
                    else:
                        self.tb[n, m] = self.tb[n, m] * (1 - self.gamma)

            for n in range(self.tb.shape[0]):
                for m in range(self.tb.shape[1]):
                    if o:
                        if m > 0:
                            tb_new[n, m] = self.tb[n, m-1] * self.mu(n, m)
                        else:
                            tb_new[n, m] = 0.0
                    else:
                        if n > 0:
                            tb_new[n, m] = self.tb[n-1, m] * self.mu(n, m)
                        else:
                            tb_new[n, m] = 0.0
            z = 0.0
            for n in range(self.tb.shape[0]):
                for m in range(self.tb.shape[1]):
                    z += tb_new[n, m]
                    # print(z)
            for n in range(self.tb.shape[0]):
                for m in range(self.tb.shape[1]):
                    self.tb[n, m] = tb_new[n, m] / z

            print(o, z, '\n', self.tb)


agent = DBMAgent(0.1, 0.5, 0.1, 0.2, outcomes)
agent.turn()
agent.outcomes


True 0.075 
 [[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
True 0.46830378435344244 
 [[0.         0.20052117 0.79947883 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.  

[True, True, True, True, True, True, False, False]

In [ ]:
n = len(outcomes)
tb = np.zeros((n+1,n+1))
tbl = np.mat((n+1, n+1))
t = []
tb[0,0] = 1
p = 0.0
gm = 0.2
for n in range(tb.shape[0]):
    for m in range(tb.shape[1]):

        def mu(n,m):
            if n==0 and m==0:
                a = 0.1
                b = 0.5
            elif n==0:
                a = 0.1
                b = 0.5 + m
            elif m==0 :
                a = 0.1 + n
                b = 0.5
            else:
                a = 0.1 + n
                b = 0.5 + m
            return a / (a+b)
        # print(n,m)
        # tb[n, m] =  1
        # tb[n, m-1] = 0
        # tbl = tb
        # t.append(tbl)
        for o in outcomes:
            if o :
               tb[n,m] = 1
               tb[n,m] *= (1-gm)
               tb[n-1, m] = 0
               tb[n-1, m] += gm
               u = mu(n-1, m)
               z = tb[n-1,m] + tb[n,m] #gm*tb[n-1,m] + (1-gm)*tb[n,m]
               tb[n,m] = tb[ n-1, m] * u / z
               tb[0, m] = 0
               # print(u, z, tb[n,m])
            else:
                # p = 1 - np.random.beta(0.1 + n, 0.5 + m)
                tb[n,m] = 1
                tb[n,m] *= (1-gm)
                tb[n, m-1] = 0
                tb[n, m-1] += gm
                u = mu(n, m-1)
                z = tb[n ,m-1] + tb[n,m] #gm*tb[n ,m-1] + (1-gm)*tb[n,m]
                tb[n,m] = tb[ n, m-1] * u  / z
                tb[n,0] = 0

        print(o, (n,m), '\n', tb)
